version: "2"

networks:
  mysql_server:

services:
  mysqldb_service:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=coffeedb
    ports:
      - "3306:3306"
    volumes:
      - ../sql:/docker-entrypoint-initdb.d
    container_name: mysqldb
    networks:
      - mysql_server
  # mysql_server_service:
  #   image: mysql-go-server
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - DB_URL=mysqldb:3306
  #     - DB_USER=root
  #     - DB_PASSWORD=password
  #     - DB_NAME=coffeedb
  #   depends_on:
  #     - mysqldb_service
  #   container_name: mysql-go-server
  #   networks:
  #     - mysql_server
