version: "2"

networks:
  coffee-hai-network:

services:
  redis-db:
    image: redis:alpine
    ports:
      - 6379:6379
    container_name: redis-db

  redis-go-server:
    build:
      context: .
      dockerfile: ./deployments/Dockerfile.dev
    image: redis-go-server:latest

    environment:
      - REDIS_DB_URL=redis-db:6379
      - REDIS_DB_PASSWORD=
      - REDIS_DB=0
    ports:
      - 5000:8080
    depends_on:
      - redis-db
    container_name: redis-go-server
