version: "2"

networks:
  coffee-hai-network:

services:
  mysqldb_service:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=coffeedb
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    container_name: mysqldb
    networks:
      - coffee-hai-network
  mysql-go-server:
    build:
      context: .
      dockerfile: ./deployments/Dockerfile.dev
    image: mysql-go-server:latest
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      - DB_URL=mysqldb:3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=coffeedb
    depends_on:
      - mysqldb_service
    container_name: mysql-go-server
    networks:
      - coffee-hai-network
